### ISSUE TITLE
line break style problem when publishing from Linux/OSX

### ISSUE THREAD

**Issue by matthung0807** [curist/splendor#1]
Similar problem like this issue but reverse. [npm publish from Windows handles CRLF incorrectly](https://github.com/npm/npm/issues/2097)

Cause errors below when execute `npm start`

so Windows user will GG

```
> ERROR in ./app/AI/helpers.js

D:\Matt\splendor\app\AI\helpers.js
   1:28  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

   2:44  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

   3:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

   4:24  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

   5:43  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

**Comment by curist** [comment]
I suspect it's about your editor saving files, and covert the line break to windows' CRLF,
so eslint throws errors.

If you are using sublime text, please check http://stackoverflow.com/questions/11899843/fixing-sublime-text-2-line-endings to set sublime to save files in unix's line ending ( line break ).

**Comment by matthung0807** [comment]
Problem solved, finally.
Before cloning the project, use `$ git config --global core.autocrlf false` in Git Bash to keep the line break as it is instead of turning into CRLF automatically on Windows system.
for more information, please refer to
 [Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/)
[Git 客製化 - Git 配置](https://git-scm.com/book/zh-tw/v1/Git-%E5%AE%A2%E8%A3%BD%E5%8C%96-Git-%E9%85%8D%E7%BD%AE)
